theme: jekyll-theme-slate
title: Explaining COVID-19 and Thoracic Pathology Model Predictions by Identifying Informative Input Features
description: Medical Image Computing and Computer Assisted Intervention (MICCAI) 2021
